# Generated by Django 5.1.7 on 2025-06-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=10)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_for', to='academics.schedule')),
                ('subjects', models.ManyToManyField(related_name='classes_given_in', to='academics.subject')),
            ],
        ),
    ]
