# Generated by Django 5.1.7 on 2025-06-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('overall_status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Incomplete', 'Incomplete')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student')),
            ],
        ),
    ]
