# Generated by Django 5.1.7 on 2025-06-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classes_schedule_alter_classes_subjects_and_more'),
        ('teachers', '0003_alter_teacher_class_assigned_alter_teacher_home_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='schedule',
            field=models.ForeignKey(default='No schedule', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='class_for', to='academics.schedule'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='subjects',
            field=models.ManyToManyField(blank=True, default='No subjects', related_name='classes_given_in', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, default='No Teachers', related_name='subjects', to='teachers.teacher'),
        ),
    ]
