# Generated by Django 5.1.7 on 2025-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_classes_schedule_alter_classes_subjects_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> - <django.db.models.fields.related.ForeignKey> - <django.db.models.fields.CharField>', max_length=30, unique=True),
        ),
    ]
