# Generated by Django 5.1.7 on 2025-04-04 11:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acadamics', '0001_initial'),
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrollment_date', models.DateField(default=datetime.date.today)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='acadamics.classes')),
                ('histories', models.ManyToManyField(related_name='students', to='acadamics.history')),
                ('homeroom_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_students', to='teachers.teacher')),
                ('parents', models.ManyToManyField(related_name='children', to='parents.parent')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='acadamics.schedule')),
                ('subjects', models.ManyToManyField(related_name='students', to='acadamics.subject')),
                ('teachers', models.ManyToManyField(related_name='students', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
    ]
