# Generated by Django 5.1.7 on 2025-06-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_class_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='description',
            field=models.CharField(default=models.CharField(default='tuition', max_length=100), max_length=200),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='name',
            field=models.CharField(default='tuition', max_length=100),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='payment_code',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> - <django.db.models.fields.CharField> - <django.db.models.fields.DateField>', editable=False, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer')], default='Transfer', max_length=10),
        ),
        migrations.DeleteModel(
            name='PaymentCategory',
        ),
    ]
