# Generated by Django 5.1.7 on 2025-06-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_history'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staffs.staff')),
                ('specialization', models.CharField(max_length=255)),
                ('class_assigned', models.ManyToManyField(related_name='teachers', to='academics.classes')),
            ],
            options={
                'abstract': False,
            },
            bases=('staffs.staff',),
        ),
    ]
