# Generated by Django 5.1.7 on 2025-04-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staffs.staff')),
                ('specialization', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('staffs.staff',),
        ),
    ]
