# Generated by Django 5.1.7 on 2025-06-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_grade'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='home_room',
            field=models.ManyToManyField(related_name='head_teacher', to='academics.classes'),
        ),
    ]
