# Generated by Django 5.1.7 on 2025-06-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_teachers'),
        ('teachers', '0002_teacher_home_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_assigned',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='academics.classes'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='home_room',
            field=models.ManyToManyField(blank=True, null=True, related_name='head_teacher', to='academics.classes'),
        ),
    ]
