# Generated by Django 5.1.7 on 2025-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_classes_schedule_alter_classes_subjects_and_more'),
        ('teachers', '0003_alter_teacher_class_assigned_alter_teacher_home_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_assigned',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academics.classes'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='home_room',
            field=models.ManyToManyField(blank=True, related_name='head_teacher', to='academics.classes'),
        ),
    ]
