# Generated by Django 5.1.7 on 2025-07-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_grade_unique_together_grade_grade_id'),
        ('teachers', '0004_alter_teacher_class_assigned_alter_teacher_home_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='home_room',
        ),
        migrations.AddField(
            model_name='teacher',
            name='home_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_teacher', to='academics.classes'),
        ),
    ]
