# Generated by Django 5.1.7 on 2025-04-04 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acadamics', '0001_initial'),
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='homeroom_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teachers',
            field=models.ManyToManyField(related_name='classes', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grades', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='history',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='acadamics.schedule'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='acadamics.subject'),
        ),
        migrations.AddField(
            model_name='classes',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', to='acadamics.subject'),
        ),
        migrations.AddField(
            model_name='totalgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_grades', to='students.student'),
        ),
        migrations.AddField(
            model_name='totalgrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_grades', to='acadamics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'assessment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='totalgrade',
            unique_together={('student', 'subject')},
        ),
    ]
