# Generated by Django 5.1.7 on 2025-04-04 11:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(max_length=100)),
                ('hiring_date', models.DateField(default=datetime.date.today)),
                ('salary', models.FloatField()),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffs.bankaccount')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
